# Generated by Django 4.0.6 on 2022-07-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='도구이름')),
                ('kind', models.CharField(max_length=50, verbose_name='도구종류')),
                ('description', models.TextField(verbose_name='도구설명')),
            ],
        ),
    ]
