# Generated by Django 4.0.6 on 2022-07-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('photo', models.ImageField(blank=True, upload_to='ideas/%Y%m%d', verbose_name='사진')),
                ('content', models.TextField(verbose_name='컨텐츠')),
            ],
        ),
    ]
